project: 
  type: website

website: 
  page-navigation: true
  title: "My Hitchhiker Guide to AI" 
  site-url: "https://knabenphysik.github.io/ai_note" 
  repo-url: "https://github.com/knabenphysik/ai_note"
  repo-actions: [edit, source, issue]
  favicon: images/favicon.ico
  
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)."
    left: "Draft,&copy; [CC BY-SA](https://creativecommons.org/licenses/by-sa/4.0/deed.en)"
    center:
      - text: "License"
        href: content/license.qmd
  
  sidebar:
    background: "#D9E3E4"
    logo: "https://img.freepik.com/premium-vector/artificial-intelligence-logo-icon-vector-symbol-ai-deep-learning-blockchain-neural-network-concept-machine-learning-artificial-intelligence-ai_230610-480.jpg"
    favicon: images/favicon.ico
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://knabenphysik.github.io/ai_note
        text: "Open Data Science"
      - icon: github
        href: https://github.com/knabenphysik/ai_note
        text: "AI Note"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Introduction
      - href: content/00_intro-ml-life-cyle.qmd
        text: Machine Learning Life Cycle
      - href: content/01_data_collection.qmd
        text: 01 - Data Collection        
      - href: content/02_eda.qmd
        text: 02 - EDA
      - href: content/03_data_labelling.qmd
        text: 03 - Data Labelling
      - href: content/04_learning.qmd
        text: 04 - Model Learning
      - href: content/05_evaluation.qmd
        text: 05 - Model Evaluation
      - href: content/06_deployment.qmd
        text: 06 - Model Deployment & Monitoring

format:
  html:
    theme:
      light: [cosmo, theme.scss] 
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

bibliography: references.bib 
csl: nature.csl
  
